    openapi: 3.0.0
    info:
      title: API demo bank
      description: API qui emule la récuperation des comptes d'un utilisateur
      version: 0.1.9
    servers:
      - url: http://localhost:8000/
        description: Server en cours de développement (local)
      - url: http://staging-api.example.com
        description: Internal staging server for testing
    paths:
      /health:
        get:
          summary: Returns ok if server is alive
          description: ""
          responses:
            '200':    # status code
              description: Just OK
              content:
                text/plain; charset=utf-8:
                  schema:
                    type: string
                    example: ok